extends Node

enum Seeds {CORN, TOMATO, PUMPKIN, WHEAT}
enum Tools {HOE, AXE, WATER, FISH, SEED, SWORD}
enum Style {BASIC, COWBOY, ENGLISH, BASEBALL, BEANIE, STRAW, CAP}
enum State {DEFAULT, FISHING, BUILDING, SHOP}
enum Machine {SPRINKLER, FISHER, SCARECROW, DELETE}
enum Item {WOOD, APPLE, TOMATO, CORN, WHEAT, PUMPKIN, FISH}
enum Shop {MAIN, HAT}
var forecast_rain: bool = false
